version: '3.9'

services:
  app:
    image: sumitroajiprabowo/go-snmp-olt-zte-c320:latest
    container_name: go-snmp-olt-zte-c320
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_MIN_IDLE_CONNECTIONS=200
      - REDIS_POOL_SIZE=12000
      - REDIS_POOL_TIMEOUT=240
      - SNMP_HOST=192.168.213.174
      - SNMP_PORT=161
      - SNMP_COMMUNITY=homenetro
    depends_on:
      - redis
    ports:
      - "8081:8081"

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - "6379:6379"