version: '3.9'

services:
  app:
    restart: always
    container_name: go-snmp-olt-zte-c320
    build:
      context: .
      target: dev
    command: air -c .air.toml
    volumes:
      - ./:/app
    ports:
      - "8081:8081"